### ISSUE TITLE
Radio buttons on EDD aren't styled like in PSD

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/azera-luxury#14]
@c0sm1n87 - se poate face ? :D 

![screen shot 2016-08-19 at 18 59 58](https://cloud.githubusercontent.com/assets/7841556/17815931/30535efe-663f-11e6-847a-ca9bcb8c71c4.png)

**Comment by c0sm1n87** [comment]
radio buttons nu pot fi styled prin css, trebuie folosita ceva librarie JS.. dupa parerea mea va aduce mai multe probleme decat merita.

**Comment by cristianraiber** [comment]
How about this: http://code.stephenmorley.org/html-and-css/styling-checkboxes-and-radio-buttons/
