### ISSUE TITLE
Hover on products, doesn't have separator like in PSD

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/azera-luxury#15]
See this: https://drive.google.com/drive/folders/0B-7njI0WHx32VllsdUVUOHMxX0U
See screenshot: 

---

![screen shot 2016-08-19 at 19 01 27](https://cloud.githubusercontent.com/assets/7841556/17815952/6338e302-663f-11e6-83df-97af0864c037.png)

**Comment by c0sm1n87** [comment]
nu prea am cum sa pun separatorul acolo din cauza ca ar trebui sa ii adaug un background solid ca sa aiba o distanta intre marginea din stanga si marginea dreapta. daca as adauga acolo separatorul, va arat asa: 

![try1](https://cloud.githubusercontent.com/assets/10389279/17816536/4ec81b38-6642-11e6-8657-db7ebc22b952.jpg)

adaugandu`i un solid color background, rezolv o problema .. dar nu prea :

![try2](https://cloud.githubusercontent.com/assets/10389279/17816571/75f223ca-6642-11e6-8e72-a53d441a89ae.jpg)

am ales sa las doar o simpla linie, e mai classy

**Comment by cristianraiber** [comment]
Sau ar putea fi facut cu un :before si un :after unde liniile alea nu au width 100% :)

**Comment by cristianraiber** [comment]
@c0sm1n87 - any word on this?

**Comment by cristianraiber** [comment]
Can't be implemented to actually look good.
