### ISSUE TITLE
Readme file missing

### ISSUE THREAD

**Issue by rodica-andronache** [MachoThemes/azera-luxury#25]
@cristianraiber can you please add a readme with all the licensing for all resouces?

**Comment by cristianraiber** [comment]
@rodica-andronache - on it :)

**Comment by rodica-andronache** [comment]
@cristianraiber the tags are not updated as in style.css.
Should update the theme name to match the one in style.css , Azera Shop Luxury.

**Comment by cristianraiber** [comment]
@c0sm1n87 - please check this.

**Comment by rodica-andronache** [comment]
@cristianraiber @c0sm1n87 how is this going? :)

**Comment by cristianraiber** [comment]
@rodica-andronache - have you checked this: 862ef7aebdfe615f56aa9adc27453dfee6e49d26 ?

**Comment by rodica-andronache** [comment]
@cristianraiber yes, I checked that, but it's not fixing all the  remaining issues

**Comment by cristianraiber** [comment]
@rodica-andronache - https://github.com/Codeinwp/azera-shop-luxury/blob/production/Readme.md. If you're referring to the remaining open issues, we'll have a look tomorrow

**Comment by rodica-andronache** [comment]
@cristianraiber neither this issue is fixed. The theme name and tags in the file you mentioned are not the same as in https://github.com/Codeinwp/azera-shop-luxury/blob/production/style.css

**Comment by cristianraiber** [comment]
@rodica-andronache - please add @c0sm1n87 as a commiter to this repo. cc @ineagu

**Comment by rodica-andronache** [comment]
he was added as a collaborator. he just needs to aswer to the request
