### ISSUE TITLE
Blog header

### ISSUE THREAD

**Issue by rodica-andronache** [MachoThemes/azera-luxury#26]
needs some spacing
http://prntscr.com/cfjb9p

**Comment by cristianraiber** [comment]
@rodica-andronache - that's happening because it's missing the site tagline. Bug is coming from parent theme.

**Comment by rodica-andronache** [comment]
http://prntscr.com/cfk1dj this is how the parent theme looks

**Comment by rodica-andronache** [comment]
This doesn't seem to be fixed @cristianraiber

**Comment by rodica-andronache** [comment]
@c0sm1n87 cum merge aici?

**Comment by cristianraiber** [comment]
@rodica-andronache - bug-ul asta vine din tema parinte. Activeaza-o, nu pune tagline si-o sa vezi aceeasi problema.

**Comment by rodica-andronache** [comment]
@cristianraiber nu inteleg . Eu zic de pagina de blog pt care sunt niste setari in customizer. In tema parinte arata ok si cand subtitlul nu e setat, si cand e. http://prntscr.com/d03vnq

In child, nu arata bine, nici cu subtitlu nici fara http://dev2.themeisle.com/azera-shop-luxury/blog/

Daca voi vedeti altceva, puteti sa-mi spuneti

**Comment by rodica-andronache** [comment]
@c0sm1n87 aici ar mai fi spatiul asta dintre imagine si meniu http://prntscr.com/d44yza
