### ISSUE TITLE
Hover effect

### ISSUE THREAD

**Issue by rodica-andronache** [MachoThemes/azera-luxury#28]
http://prntscr.com/cfjc1n Is this the way it's suppose to be?

**Comment by cristianraiber** [comment]
@rodica-andronache - Yep.

**Comment by rodica-andronache** [comment]
everywhere? http://prntscr.com/cfjd50 for me it looks bad

**Comment by cristianraiber** [comment]
@rodica-andronache - that's how the design was approved ... this is default browser behaviour to have an underline on hover.  Maybe it's just a personal opinion?

**Comment by rodica-andronache** [comment]
yes, maybe just my opinion. Just that is no uniformity between the elements. Some buttons have a certain color on hover, some other color, some have the text underlined on hover etc. I suppose that all this effects were not covered in the design, but I may be wrong

**Comment by cristianraiber** [comment]
@rodica-andronache - I will have our designer take a look over this.

**Comment by cristianraiber** [comment]
@rodica-andronache - @c0sm1n87 will take care of this in an update.
