### ISSUE TITLE
CSS compatibility with woocommerce

### ISSUE THREAD

**Issue by rodica-andronache** [MachoThemes/azera-luxury#31]
for example http://prntscr.com/cfjh76

**Comment by cristianraiber** [comment]
@rodica-andronache - check parent theme.

**Comment by rodica-andronache** [comment]
for what?

**Comment by rodica-andronache** [comment]
http://prntscr.com/ch3lsv @cristianraiber

**Comment by cristianraiber** [comment]
@c0sm1n87 - can you please check this?

**Comment by c0sm1n87** [comment]
@cristianraiber @rodica-andronache  - I made both buttons same height.. :) thought that it will look better. I will resize them later today.
