### ISSUE TITLE
Why are some of the sections overridden?

### ISSUE THREAD

**Issue by rodica-andronache** [MachoThemes/azera-luxury#34]
For example azera_shop_logos_section.php , from what I can see the only difference is this http://prntscr.com/cfjrbe . Couldn't this be changes with css  in the child?

**Comment by cristianraiber** [comment]
@c0sm1n87 - can you please take a look at this?

**Comment by c0sm1n87** [comment]
Hello @rodica-andronache, 

You are correct, you can overwrite the default styles of the parent theme, but why would you apply a dark color background on a class that's called "white-bg" ?

**Comment by rodica-andronache** [comment]
Hi,

It's not ideal but I think it's better than to overwrite files in the child themes, files that can be updated in the parent, and after that, it will cause problems in the child theme
