### ISSUE TITLE
Single product page

### ISSUE THREAD

**Issue by rodica-andronache** [MachoThemes/azera-luxury#43]
- [x] http://prntscr.com/csiwe9
- [x] Clicking on Description/Reviews is not working corectly http://prntscr.com/csix4x

**Comment by c0sm1n87** [comment]
![description](https://cloud.githubusercontent.com/assets/10389279/19301773/d11c2bfa-9069-11e6-9c68-13590a45dbb9.jpg)

**Comment by rodica-andronache** [comment]
@c0sm1n87 tab-urile functioneaza ok acum, Dar mai sunt problemele cu fontul titlului si moneda. Cand crezi ca pot fi rezolvate problemele astea?

**Comment by cristianraiber** [comment]
@rodica-andronache - asta e duplicate #44?

**Comment by rodica-andronache** [comment]
Nu, asta e pt pagina de single. au fost rezolvate ce ziceam mai sus. Ar mai fi:

http://prntscr.com/d02mo1

http://prntscr.com/d02n6m

**Comment by cristianraiber** [comment]
@c0sm1n87 - vezi mai sus :)

**Comment by rodica-andronache** [comment]
nici notificarile nu au legatura cu design-ul http://prntscr.com/d02psu

**Comment by rodica-andronache** [comment]
Variable products on cart page http://prntscr.com/d02qwh

**Comment by c0sm1n87** [comment]
8eb066997a5a1476a72d074a04a1b59ee84de91a

**Comment by rodica-andronache** [comment]
@c0sm1n87 aici nu au fost rezolvate decat o parte din problemele deja mentionate http://prnt.sc/d02mo1 http://prnt.sc/d02n6m . oricum ar trebui verificate paginile in totalitate, sa arate ok si consistent pe total si ca in psd. Sunt chestii destul de vizibile

**Comment by rodica-andronache** [comment]
@c0sm1n87 toate astea mentionate mai sunt  cand mai pot fi rezolvate? :)

**Comment by c0sm1n87** [comment]
@rodica-andronache first thing tomorrow.
