### ISSUE TITLE
Shop page

### ISSUE THREAD

**Issue by rodica-andronache** [MachoThemes/azera-luxury#44]
- [x] http://prntscr.com/csjcp8
- [x] http://prntscr.com/csjdbo not like psd

**Comment by rodica-andronache** [comment]
@c0sm1n87 problema cu taburile pare sa se fi rezolvat, nu stiu exact de ce nu mergea atunci.

Mai sunt celelalte probleme de rezolvat :) ar trebui sa arate ca in psd tema . Mersi

**Comment by c0sm1n87** [comment]
![ordering-select](https://cloud.githubusercontent.com/assets/10389279/19599689/a45936e2-97aa-11e6-8389-529cd08645e8.PNG)
![spacing](https://cloud.githubusercontent.com/assets/10389279/19599690/a45c1efc-97aa-11e6-94c3-3b8f3fff1667.PNG)
![price](https://cloud.githubusercontent.com/assets/10389279/19599708/b463432a-97aa-11e6-87ce-12e71338f7ea.PNG)

**Comment by rodica-andronache** [comment]
@c0sm1n87 nu stiu exact ce vrei sa-mi arati in poza :) ca sunt 60 px distanta in psd? si in tema asa sunt? http://dev2.themeisle.com/azera-shop-luxury/shop/

Plus, mai sunt diferentele, cu butonul de sortare, moneda

**Comment by rodica-andronache** [comment]
@c0sm1n87  @cristianraiber  cam in cat timp pot fi terminata tema? :)

**Comment by cristianraiber** [comment]
@rodica-andronache - ai verificat si branch-ul de dev? https://github.com/Codeinwp/azera-shop-luxury/tree/development

**Comment by rodica-andronache** [comment]
@cristian-ungureanu ok, mai verific odata pe local, cred ca nu s-a actualizat bine aici http://dev2.themeisle.com/azera-shop-luxury/

**Comment by cristianraiber** [comment]
@rodica-andronache - ai dat ping-ul gresit :D

**Comment by rodica-andronache** [comment]
Ok, problemele alea au fost rezolvate. 
Dar mai sunt astea:

- http://prntscr.com/d02dbr

- http://prntscr.com/d02ezi

- pe mobil ar trebui sa fie aliniat asta http://prntscr.com/d02gch

**Comment by cristianraiber** [comment]
@rodica-andronache - cool, we'll take care of the new ones :)
