### ISSUE TITLE
Frontpage issues

### ISSUE THREAD

**Issue by rodica-andronache** [MachoThemes/azera-luxury#46]
http://prntscr.com/d02sci

http://prntscr.com/d02t96

imaginea de pe prima pagina e foarte blurata http://prntscr.com/d02v43

**Comment by c0sm1n87** [comment]
@rodica-andronache in legatura cu al2lea screen. nu prea am cum sa fac designul ca in PSD. am incercat diferite scenarii, dar nu prea iese cum ar trebui. Din cauza asta am optat sa las doar un separator simplu.  Daca backgroundul ar fi fost albastru inchis ( fara transparenta ), ar fi fost usor de implementat.

**Comment by rodica-andronache** [comment]
@c0sm1n87 nu prea am inteles ce spui. Care e legatura intre bara aia si background?

**Comment by c0sm1n87** [comment]
@rodica-andronache ca sa pot suprapune shape-ul ala peste linie, trebuie sa ii dau un solid color background ( altfel ar fi striked through .. gen ~~asa~~ ). Problema e ca backgroundul containerului este transparent si nu arata bine .. exemplu:

![sep](https://cloud.githubusercontent.com/assets/10389279/19964634/84fa14a8-a1cb-11e6-986e-7295a2d829c7.jpg)

Alta solutie de tip before,after - nu ar arata prea bine ( trebuie sa le dau un width fix ) across devices / resolutions

**Comment by rodica-andronache** [comment]
@c0sm1n87 si ce solutie propui? acum nu arata prea bine doar cu linia aia

**Comment by rodica-andronache** [comment]
nici pretul nu e afisat ca in psd http://prntscr.com/d44uhb

**Comment by cristianraiber** [comment]
@rodica-andronache - treaba cu linia si cu separatorul custom o discutasem eu cu @ineagu pe Slack. A ramas ca n-avem ce-i face, din pacate. Si eu am insistat pt. separator ca in PSD da' nu se paote realiza intr-un mod ok.

**Comment by rodica-andronache** [comment]
ok

**Comment by rodica-andronache** [comment]
@cristianraiber cam cand crezi ca pot fi rezolvate toate celelalte probleme?
