### ISSUE TITLE
NU inteleg cum se face contact page-ul ca in demo :))

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/azera-luxury#5]

**Comment by c0sm1n87** [comment]
trebuie sa faci o harta, un contact form si pe urma sa folosesti templateul Contact Page - am stilizat pe cat se putea ( icoane in inputuri, e deja SF + harta nu am cum sa controlez - pluginul trebuie updatat pentru ca de ceva vreme ai nevoie de cheie sa generezi google maps )

**Comment by cristianraiber** [comment]
Am reusit ... pt. a ajunge sa faci pagina de contact ca-n demo, trebuie sa te duci pe pagina de contact si de acolo abia sa dai Customize. Vei gasi 2 input-uri in customizer pt. map si contact form :| Greu dle, greu...
