### ISSUE TITLE
Themeisle page images

### ISSUE THREAD

**Issue by rodica-andronache** [MachoThemes/azera-luxury#53]

**Comment by claudiuvertistudio** [comment]
[luxury.zip](https://github.com/Codeinwp/azera-shop-luxury/files/611314/luxury.zip)

**Comment by rodica-andronache** [comment]
poti sa refaci prima imagine si ultimele 3 din slider pt arata cam blurate https://themeisle.com/themes/azera-shop-luxury/ ?
si imaginea de la WooCommerce integration un pic mai mare sa se potriveasca cu celelalte?

**Comment by claudiuvertistudio** [comment]
[yyy.zip](https://github.com/Codeinwp/azera-shop-luxury/files/613465/yyy.zip)

nu am ce sa fac ca sa nu se mai vada blurate
