### ISSUE TITLE
'Shop' nu afiseaza nimic 

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/azera-luxury#6]

**Comment by c0sm1n87** [comment]
n`are cum sa fie de la tema.. la mine se vede ok 

![fireshot screen capture 171 - products azera - localhost_azera_shop](https://cloud.githubusercontent.com/assets/10389279/17775737/522e0796-6562-11e6-96c2-839490c29e55.png)

**Comment by cristianraiber** [comment]
@c0sm1n87 will test this again
